---
permalink: linux-administration/concept_operation_with_a_single_filespec_on_multiple_storage_objects.html 
sidebar: sidebar 
keywords: snap, snapdrive, filespec, storage, objects, single, operation 
summary: 'SnapDrive per UNIX visualizza un messaggio di errore quando l"amministratore non dispone dell"autorizzazione necessaria per eseguire le operazioni di storage su più oggetti di storage.' 
---
= Operazioni con un singolo filespec su più oggetti storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX visualizza un messaggio di errore quando l'amministratore non dispone dell'autorizzazione necessaria per eseguire le operazioni di storage su più oggetti di storage.

`_Filespec: Filespec can be anyone of file system, host volume, disk group, or LUN_`

[listing]
----
[root]# snapdrive storage create -fs /mnt/testfs -lun storage_array1:/vol/vol1/lun2 -lun storage_array1:/vol/vol2/lun2  -lunsize 100m
0002-332 Admin error:SD.Storage.Write access denied on volume storage_array1:/vol/vol1 for user unix_host\root on Operations Manager server ops_mngr_server
SD.Storage.Write access denied on volume storage_array1:/vol/vol2 for user unix_host\root on Operations Manager server ops_mngr_server
----
In questo esempio, il filespec si estende su due volumi di sistema storage, vol1 e vol2. L'amministratore (root) di unix_host non dispone di `SD.Storage.Write` accesso su entrambi i volumi. Pertanto, SnapDrive per UNIX visualizza un messaggio di errore per ogni volume. Per procedere con `storage create`, L'amministratore (root) deve chiedere all'amministratore della console di Operations Manager di concedere `SD.Storage.Write` accesso su entrambi i volumi.
