---
permalink: linux-administration/concept_considerations_for_supporting_vfiler_unit.html 
sidebar: sidebar 
keywords: snap, snapdrive, vfiler, support, issues, unit 
summary: 'SnapDrive per UNIX supporta le operazioni SnapDrive su un"unità vFiler creata su un volume FlexVol. Tuttavia, SnapDrive per UNIX non supporta le unità vFiler se si utilizza Fibre Channel.' 
---
= Problemi di supporto dell'unità vFiler
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX supporta le operazioni SnapDrive su un'unità vFiler creata su un volume FlexVol. Tuttavia, SnapDrive per UNIX non supporta le unità vFiler se si utilizza Fibre Channel (FC).

È necessario conoscere alcune considerazioni relative al supporto delle unità vFiler da parte di SnapDrive per UNIX:

* Le operazioni SnapDrive non sono supportate su un'unità vFiler creata su un qtree.
+
Queste operazioni sono consentite se l'unità vFiler possiede l'intero volume di storage.

* Quando si configura SnapDrive per supportare le unità vFiler, è necessario assicurarsi che i percorsi di gestione e dati non siano configurati per un'interfaccia su vFiler0.
* In Data ONTAP, operativo in 7-Mode, è necessario assicurarsi che la variabile di configurazione Data ONTAP `vfiler.vol_clone_zapi_allow` è impostato su `on` Per connettersi a una copia Snapshot per un volume o un LUN in un'unità vFiler.

