---
permalink: linux-administration/concept_guidelines_for_usingthe_storage_deletecommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, delete, command, guidelines, file 
summary: Il comando di eliminazione dello storage SnapDrive presenta alcune limitazioni in SnapDrive per UNIX. 
---
= Linee guida per l'utilizzo del comando di eliminazione dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `snapdrive storage delete` Command presenta alcune limitazioni in SnapDrive per UNIX.

* Quando si elimina un file system, SnapDrive per UNIX rimuove sempre il punto di montaggio del file system.
+
Gli host Linux consentono di collegare più file system a un singolo punto di montaggio. Tuttavia, SnapDrive per UNIX richiede un punto di montaggio univoco per ogni file system. Il `snapdrive storage delete` il comando non riesce se viene utilizzato per eliminare i file system collegati a un singolo punto di montaggio.

* Se si utilizza `-lun` Opzione per specificare il nome di un LUN membro di un gruppo di dischi host o di un file system, la `snapdrive storage delete` comando non riuscito.
* Se si utilizza `-lun` Opzione per specificare il nome del LUN non rilevato dal software multipathing sull'host, la `snapdrive storage delete` comando non riuscito.



NOTE: `snapdrive storage delete` Il comando non riesce durante l'utilizzo del LUN RDM, se l'igroup di mappatura ha più di due nomi di porte mondiali (WWPN) nelle release precedenti a SnapDrive 5.2 per UNIX.
