---
permalink: linux-administration/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, autosupport, message, example 
summary: SnapDrive per UNIX fornisce esempi per diversi scenari. Il contenuto di un messaggio AutoSupport in tutti gli esempi è sostanzialmente lo stesso indipendentemente dal sistema operativo in uso. 
---
= Esempi di messaggi AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX fornisce esempi per diversi scenari. Il contenuto di un messaggio AutoSupport in tutti gli esempi è sostanzialmente lo stesso indipendentemente dal sistema operativo in uso.

Esempio: Aggiunta di un nuovo sistema storage

L'esempio seguente è un messaggio inviato da un host denominato `_x336-207-58_`:

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="sduvs2 configured"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp
----
Esempio: Riavviare il Daemon

Quando si riavvia il daemon, SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage:

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage, se `dfm` è configurato e. `rbac-method` è impostato su `dfm`:

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=dfm, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=Yes, Protocol=fcp"
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage, se `dfm` è configurato e. `rbac-method` è impostato su nativo.

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=Yes, Protocol=fcp"
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage quando un `snap create` operazione riuscita:

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=3, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=iscsi, snapshot_name=dg_snap"
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage quando l'operazione show all dello storage ha esito positivo:

[listing]
----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="general"
        subject="protos=fcp, Connect Luns=8, dgs=4, hvs=3, fs=3, host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----