---
permalink: linux-administration/concept_operation_with_multiple_storage_objects.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, objects, multiple, error, authorized, user 
summary: 'L"esempio seguente mostra il messaggio di errore che si riceve quando non si è un utente autorizzato a eseguire l"operazione specifica.' 
---
= Operazioni con più oggetti di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'esempio seguente mostra il messaggio di errore che si riceve quando non si è un utente autorizzato a eseguire l'operazione specifica.

[listing]
----
[john]$ snapdrive storage show –all

Connected LUNs and devices:

device filename   adapter  path  size  proto  state  clone  lun path                           backing Snapshot
----------------  -------  ----  ----  -----  -----  -----  --------                           ---------------
/dev/sdao            -     -     200m  iscsi  online  No    storage_array1:/vol/vol2/passlun1           -
/dev/sda1            -     -     200m  fcp    online  No    storage_array1:/vol/vol2/passlun2           -

Host devices and file systems:

dg: testfs1_SdDg                dgtype lvm
hostvol: /dev/mapper/testfs1_SdDg-testfs1_SdHv  state: AVAIL
fs: /dev/mapper/testfs1_SdDg-testfs1_SdHv       mount point: /mnt/testfs1 (persistent) fstype ext3

device filename   adapter  path  size  proto  state   clone  lun path                                backing Snapshot
----------------  -------  ----  ----  -----  -----   -----  --------                                ---------
/dev/sdn             -      P    108m  iscsi  online   No    storage_array1:/vol/vol2/testfs1_SdLun         -
/dev/sdn1             -      P    108m  fcp  online   No    storage_array1:/vol/vol2/testfs1_SdLun1         -

0002-719 Warning: SD.Storage.Read access denied on volume storage_array1:/vol/vol1 for user unix_host\john on Operations Manager server ops_mngr_server
----
John è autorizzato ad elencare le entità di storage su vol2 ma non su vol1. SnapDrive per UNIX visualizza le entità di vol1 e un messaggio di avviso per vol2.


NOTE: Per `storage list`, `storage show`, `snap list`, e. `snap show` Commands SnapDrive per UNIX visualizza un avviso invece di un errore.
