---
permalink: linux-administration/concept_disconnecting_a_filespec.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, file, specification 
summary: 'È possibile scollegare una specifica del file. Nell"esempio seguente viene descritto come completare questa operazione.' 
---
= Disconnessione di una specifica di file
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile scollegare una specifica del file. Nell'esempio seguente viene descritto come completare questa operazione.

Il layout di /mnt/fs1_0 è indicato di seguito.

[listing]
----
# snapdrive storage show -fs /mnt/fs_1_0 -capabilities
raw device: /dev/sde1   mount point: /mnt/fs_1_0 (persistent) fstype ext3
allowed operations: all

device filename    adapter  path    size    proto   state   clone         lun path                                                         backing snapshot
----------------   -------  ----    ----    -----   -----   -----         --------                                                         ----------------
/dev/sde              -      P      100m    iscsi   online  flex-clone    homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1    vol1:snap2
----
Il seguente output mostra come disconnettere il file system /mnt/fs_1_0:

[listing]
----
#snapdrive snap disconnect -fs /mnt/fs_1_0
 delete file system /mnt/fs_1_0
- fs /mnt/fs_1_0 ... deleted
         - LUN homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1 ... disconnected
         - deleting volume clone ... homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot  done
----
Dopo aver scollegato il file system /mnt/fs_1_0, SnapDrive per UNIX elimina anche il volume clonato SnapDrive_vol1_0_volume_clone_from_snap2_snapshot, se vengono soddisfatte le seguenti condizioni:

* Nel volume non sono presenti LUN mappati
* Non sono presenti nuovi LUN
* Non sono presenti nuove copie Snapshot


*Eliminazione di un FlexClone non creato da SnapDrive per UNIX*: SnapDrive per UNIX non consente l'eliminazione di FlexClone non creato da esso.
