---
permalink: linux-administration/reference_storage_provisioning_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, command, provisioning 
summary: Alcuni comandi SnapDrive per UNIX vengono utilizzati per il provisioning dello storage. 
---
= Righe di comando per il provisioning dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alcuni comandi SnapDrive per UNIX vengono utilizzati per il provisioning dello storage.

Le seguenti opzioni della riga di comando vengono utilizzate per le operazioni di provisioning dello storage:

|===
| Operazione | Opzione della riga di comando 


 a| 
Creare
 a| 
`snapdrive storage create -lun _long_lun_name [lun_name ...]_ -lunsize _size_ [{ -dg | -vg } _dg_name_] [-igroupig_name [_ig_name ..._]] [{ -reserve | -noreserve }][-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create {-lvol | -hostvol} _file_spec_ [{-dg | -vg} _dg_name_]{-dgsize | -vgsize} _size_-filervol _long_filer_path_ [{-noreserve | -reserve}] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create -fs _file_spec_ -nolvm [-fsopts options ] [-mntopts options] [-nopersist] { -lun _long_lun_name_ | -filervol _long_filer_path_ } -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -filervol _long_filer_path_ -dgsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve | -noreserve }]`



 a| 
`snapdrive storage create _host_lvm_fspec_ -lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [-igroupig_name [ig_name ...]] [{ -reserve | -noreserve }]`

[NOTE]
====
È possibile utilizzare qualsiasi formato per `-file_spec` a seconda del tipo di storage che si desidera creare. (Ricordate che `-dg` è un sinonimo per `-vg`, e. `-hostvol` è un sinonimo per `-lvol`.)

Per creare un file system direttamente su un LUN, utilizzare questo formato: `-fs _file_spec_ [-nolvm -fs _type_] [-fsops _options_] [-mntopts _options_] [-vmtype _type_]`

Per creare un file system che utilizza un gruppo di dischi o un volume host, utilizzare questo formato: `-fs _file_spec_ [-fstype _type_] [-fsopts _options_] [-mntops _options_] [-hostvol _file_spec_] [-dg _dg_name_] [-vmtype _type_]`

Per creare un volume logico o host, utilizzare questo formato: `[-hostvol _file_spec_] [-dg _dg_name_] [-fstype _type_] [-vmtype _type_]`

Per creare un gruppo di dischi, utilizzare questo formato: `-dg _dg_name_ [-fstype _type_] [-vmtype _type_]`

====


 a| 
Connettersi
 a| 
`snapdrive storage connect -fs _file_spec -nolvm_ -lun _long_lun_name_ [-igroup _ig_name_ [_ig_name ..._]] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name ..._] [-igroup _ig_name_ [_ig_name ..._]][-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name ..._][-igroup _ig_name_ [_ig_name ..._]][-vmtype _type_]`



 a| 
`snapdrive storage connect -lun _long_lun_name_ [_lun_name..._][-vmtype _type_]`



 a| 
`snapdrive storage connect -fs _file_spec_ {-hostvol | -lvol} _file_spec_ -lun _long_lun_name_ [_lun_name..._] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
Scollegare
 a| 
`snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`



 a| 
`snapdrive storage disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec ..._] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ ...] ...] [-full] [-fstype _type_] [-vmtype _type_]`



 a| 
Ridimensionare
 a| 
`snapdrive storage resize {-dg | -vg} _file_spec_ [_file_spec ..._]{-growby | -growto} _size_ [_-addlun_ [-igroup _ig_name_ [_ig_name ..._]]] [{ -reseserve | -noreserve }]] [-fstype _type_] [-vmtype _type_]`



 a| 
Mostra/Elenca
 a| 
`snapdrive storage { show | list } -filer _filername_ [_filername ..._] [-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } -filervol _long_filer_path_ [_filer_path..._][-verbose] [-quiet] [-capabilities]`



 a| 
`snapdrive storage { show | list } {-all | device} [-capabilities]`



 a| 
`snapdrive storage show [-verbose] {-filer _filername_ [_filername..._] | -filervol _volname_ [_volname..._]} [-capabilities]`



 a| 
`snapdrive storage { show | list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-quiet] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -vg | -dg | -fs | -lvol |-hostvol } _file_spec_ [_file_spec ..._] [{ -vg | -dg | -fs | -lvol | -hostvol } _file_spec_ [_file_spec ..._]] [-verbose] [-quiet [-fstype _type_] [-vmtype _type_] [-status] [-capabilities]`



 a| 
`snapdrive storage { show | list } { -filer _filer_name_ [_filer_name ..._] | -filervol _long_filer_path_ [_filer_path ..._] } [-verbose] [-capabilities] [-quiet]`



 a| 
`snapdrive storage { show | list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-status] [-fstype type] [-vmtype type] [-capabilities] [-quiet]`



 a| 
Eliminare
 a| 
`snapdrive storage delete [-lun] _long_lun_name_ [lun_name...] [-fstype type] [-vmtype type]`



 a| 
`snapdrive storage delete [-vg | -dg | -fs | -lvol | -hostvol] _file_spec_ [file_spec ...] [{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [file_spec ...] ...] [-full] ] [-fstype type] [-vmtype type]`

|===
*Informazioni correlate*

xref:reference_command_line_arguments.adoc[Argomenti della riga di comando]
