---
permalink: linux-administration/reference_informationrequired_forusing_the_snapdrive_storagedisconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, command, storage 
summary: La seguente tabella fornisce le informazioni necessarie quando si utilizza il comando di disconnessione dello storage SnapDrive. 
---
= Informazioni necessarie per l'utilizzo del comando di disconnessione dello storage SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La seguente tabella fornisce le informazioni necessarie per l'utilizzo di `snapdrive storage disconnect` comando:

|===
| Requisito | Argomento 


 a| 
In base al comando immesso, è possibile rimuovere le mappature da una delle seguenti opzioni:

* LUN
+
Se si disconnettono uno o più LUN, il primo argomento deve utilizzare la forma lunga del nome del LUN, che specifica il nome del sistema di storage, il nome del volume e il nome del LUN all'interno del volume.

+
Per specificare ulteriori LUN, è possibile utilizzare solo il nome del LUN se il nuovo LUN si trova sullo stesso sistema di storage e volume del LUN precedente. In caso contrario, è possibile specificare un nuovo nome di sistema storage e un nome di volume (o semplicemente un nome di volume) per sostituire i valori precedenti.

* File system su LUN
+
Il `file_spec` dato a. `-fs` è il nome del punto di montaggio del file system. SnapDrive per UNIX individua e disconnette automaticamente il LUN associato al file system specificato.

* Gruppi di dischi o volumi
* File system su dischi o gruppi di volumi
* Volumi host o logici


Il valore immesso per l'argomento file_spec deve identificare l'entità di storage che si sta disconnettendo.



 a| 
UN LUN (`-lun`)
 a| 
`_lun_name_` (forma lunga o breve)



 a| 
Gruppo di dischi (`-dg _file_spec_`) o gruppo di volumi (`-vg _file_spec_)
 a| 
nome del disco o del gruppo di volumi



 a| 
File system (`-fs _file_spec_`)
 a| 
`_filesystem_name_`



 a| 
Volume host (`-hostvol _file_spec_`) o volume logico (`-lvol _file_spec_`)
 a| 
nome dell'host o del volume logico



 a| 
Se si desidera che SnapDrive per UNIX disconnetti lo storage specificato anche se si include al prompt dei comandi un'entità lato host che ha altre entità (ad esempio un gruppo di dischi che ha uno o più volumi host), includere `-full` al prompt dei comandi.

Se non si include questa opzione, specificare solo entità lato host vuote.



 a| 
`-full`
 a| 
~



 a| 
Se si desidera disattivare la condivisione di un file system da parte di un nodo o di un cluster host



 a| 
`-fstype`
 a| 
`_type_`



 a| 
`-vmtype`
 a| 
`_type_`



 a| 
*Opzionale:* specifica il tipo di file system e di volume manager da utilizzare per le operazioni SnapDrive per UNIX.

|===