---
permalink: linux-administration/task_adding_a_port_set_in_snapdrive.html 
sidebar: sidebar 
keywords: snap, snapdrive, vserver, port, storage, set 
summary: 'È possibile aggiungere un set di porte nel sistema di storage per comunicare con un Vserver. Si tratta di un"attività una tantum che deve essere eseguita prima di utilizzare il sistema di storage.' 
---
= Aggiunta di un set di porte in SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere un set di porte nel sistema di storage per comunicare con un Vserver. Si tratta di un'attività una tantum che deve essere eseguita prima di utilizzare il sistema di storage.


NOTE: Se si desidera eseguire l'aggiornamento a SnapDrive 5.2 per UNIX, assicurarsi che le versioni precedenti di SnapDrive per UNIX igroups siano associate manualmente alla porta impostata dall'amministratore dello storage.

Nell'esempio seguente, l'amministratore dello storage utilizza il nome del server virtuale invece di un indirizzo IP e verifica che il nome del server virtuale sia registrato su un server DNS.

.Fasi
. Immettere il seguente comando sull'host:
+
`*snapdrive portset add _portset_name filername_ [_filername..._]*`

+
`_portset_name_` è il nome del set di porte.

+
`_filername_` È il nome del Vserver.

+
[listing]
----
snapdrive portset add ps2 vs91
Added portset configuration for appliance: vs91
----
+
Il set di porte ps2 viene aggiunto correttamente in SnapDrive.


