---
permalink: linux-administration/task_configuring_management_and_data_interfaces_for_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, management, configure, data, interface, nfs, traffic 
summary: È possibile configurare più interfacce dati per una singola interfaccia di gestione in un ambiente NFS, in modo da separare il traffico di gestione dal traffico dati sul sistema storage. 
---
= Configurazione delle interfacce di gestione e dati per un sistema storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare più interfacce dati per una singola interfaccia di gestione in un ambiente NFS, in modo da separare il traffico di gestione dal traffico dati sul sistema storage.

.Fasi
. Impostare la configurazione per la nuova interfaccia di gestione:
+
`*snapdrive config set root*`

+
[listing]
----
# snapdrive config set root f3050-197-91
Password for root:
Retype password:
----
+
Di seguito viene riportato un esempio di una macchina virtuale per lo storage (SVM, precedentemente nota come Vserver).

+
[listing]
----
# snapdrive config set vsadmin clstr-vs2
Password for vsadmin:
Retype password:
----
. Configurare l'interfaccia dati per la nuova interfaccia di gestione:
+
`*snapdrive config set*`

+
[listing]
----
# snapdrive config set -mgmtpath f3050-197-91 f3050-220-91#
----
+
Nel comando precedente, `f3050-197-191` è l'interfaccia di gestione e. `f3050-220-91` è l'interfaccia dati.

+
Di seguito viene riportato un esempio di SVM.

+
[listing]
----
snapdrive config set -mgmtpath clstr-vs2  clstr-vs2-2
system name   management interface   datapath interface
-------------------------------------------------------
clstr-vs2     10.72.220.203          10.72.221.155
----
+
Nell'output, `10.72.220.203` è l'interfaccia di gestione e. `10.72.221.155` è l'interfaccia dati.


