---
permalink: linux-administration/task_creating_a_filesystem_on_a_lunand_specifying_thelun.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, file, create 
summary: È possibile creare un file system su un LUN e specificare le LUN create come parte di esso. 
---
= Creazione di un file system su un LUN e specifica del LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un file system su un LUN e specificare le LUN create come parte di esso.

.Fasi
. Utilizzare il seguente formato di comando per completare questa operazione:
+
`*snapdrive storage create _-fsfile_spec_ -nolvm [-fstype type] [-vmtype _type_] [-fsopts _options_] [-mntopts _options_] [-nopersist] -lun _long_lun_name_ -lun _size sizeig_name_ [_ig_name..._]] [{ -reserve | -noreserve }]*`

+
SnapDrive per UNIX crea il file system sul sistema di storage, sul volume e sul LUN specificati. Esegue tutte le attività associate alla preparazione e al rilevamento degli host per le LUN, nonché il mapping e la connessione delle LUN all'entità host.





== Esempio: Creazione di un file system da 100 MB su luna in acctfiler:/vol/vol1

`# snapdrive storage create -fs /mnt/acct1 -lun acctfiler:/vol/vol1/luna -lunsize 100m -nolvm`
