---
permalink: linux-administration/task_starting_the_volume_or_lun_clone_split_start.html 
sidebar: sidebar 
keywords: snap, snapdrive, clone, lun, split, volume 
summary: 'È possibile avviare un"operazione di clonazione del volume o di suddivisione del clone del LUN.' 
---
= Avvio del clone del volume o della divisione del clone del LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile avviare un'operazione di clonazione del volume o di suddivisione del clone del LUN.

.Fasi
. Immettere il seguente comando per avviare un clone del volume o una divisione del clone del LUN.
+
`*# snapdrive clone split start [-lun] _long_lun_name_ [_long_lun_name..._] | [{-dg | -vg | -fs | -hostvol | -lvol} _file_spec_ [_file_spec ..._]] [-force][-noprompt] [-dump | -dumpall]*`

+
Le seguenti opzioni possono essere utilizzate quando lo stato dello storage viene visualizzato COME NON DISPONIBILE.

+
** È possibile utilizzare `-force` opzione per avviare forzatamente l'operazione di suddivisione del clone e ricevere un messaggio di conferma dell'avvio dell'operazione.
** È possibile utilizzare `-noprompt` insieme a. `-force` opzione per avviare l'operazione di avvio del clone split senza ricevere alcun messaggio di conferma.





NOTE: Quando si avvia un'altra operazione di suddivisione dei cloni subito dopo l'interruzione di un'operazione di suddivisione dei cloni in corso, l'operazione potrebbe non riuscire. Questo problema potrebbe verificarsi se il ritardo tra l'avvio e l'arresto dell'operazione di suddivisione del clone non era sufficiente per consentire al sistema di storage di sincronizzare l'operazione di interruzione.

Nell'esempio riportato di seguito viene illustrato come suddividere un clone di un volume:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt4_0 /mnt/my_mnt3_0
Resource    Container  Required Available Storage
                       Space(MB)Space(MB) Status
--------------------------------------------------
/mnt/my_mnt4_0 f3050-220 3295   66033 AVAILABLE
             -111:aggr0
/mnt/my_mnt3_0 f3050-220  293   37707 AVAILABLE
             -112:aggr1

Job ID: B265Dbv8gh
Clone-Split for "/mnt/my_mnt4_0" is started
Clone-Split for "/mnt/my_mnt3_0" is started
----
Nell'esempio riportato di seguito viene illustrato come suddividere un clone utilizzando `-force` opzione:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force
Resource    Container Required  Available Storage
                      Space(MB) Space(MB) Status
----------------------------------------------------
/mnt/my_mnt5 f3050-220 1198   20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294  2196  NOT AVAILABLE
             -112:aggr1
Not enough space available for Clone-Split.  Do you want to continue (y/n)?y
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----
Nell'esempio riportato di seguito viene illustrato come avviare direttamente un clone utilizzando `-noprompt` opzione che significa che non viene visualizzato alcun messaggio di conferma:

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force -noprompt
Resource    Container  Required  Available Storage
                       Space(MB) Space(MB) Status
-----------------------------------------------------
/mnt/my_mnt5 f3050-220  1198     20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294     2196  NOT AVAILABLE
             -112:aggr1
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----