---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: 'Per utilizzare il multipathing in SnapDrive per UNIX, è necessario completare i passaggi che includono l"installazione e l"avvio dell"HBA. Se si utilizza una soluzione multipathing non NetApp, è necessario scaricare il pacchetto software e applicativo dal sito Web del vendor HBA.' 
---
= Abilitazione del multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare il multipathing in SnapDrive per UNIX, è necessario completare i passaggi che includono l'installazione e l'avvio dell'HBA. Se si utilizza una soluzione multipathing non NetApp, è necessario scaricare il pacchetto software e applicativo dal sito Web del vendor HBA.

Il sistema deve eseguire le versioni correnti dei componenti del sistema FC e iSCSI.

http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

.Fasi
. Installare gli HBA supportati prima di installare il software host Utilities appropriato.
+

NOTE: SnapDrive per UNIX supporta HBA multivendor.

. Avviare il servizio HBA.
+
Se il servizio HBA non è in esecuzione, viene visualizzato il seguente messaggio di errore quando si eseguono i comandi SnapDrive per UNIX, ad esempio `snapdrive storage create` e. `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
È necessario verificare che il numero di percorsi richiesto sia attivo e in esecuzione. È possibile verificare i percorsi utilizzando `sanlun` Utility inclusa nel software host Utilities. Ad esempio, nella configurazione multipathing FC, è possibile utilizzare `sanlun fcp show adapter -v` comando.

+
Nell'esempio seguente, sono presenti due porte HBA (fcd0 e fcd1) collegate all'host e funzionanti (stato della porta). È possibile disporre di un solo HBA o iSCSI Initiator ed è necessario configurare il multipathing fornendo più di un percorso per i LUN di destinazione.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Se su un host è attivato il multipathing, sono visibili più percorsi per lo stesso LUN. È possibile utilizzare `sanlun lun show all` per verificare i percorsi. Nell'esempio seguente, è possibile trovare più percorsi per lo stesso LUN (`fish: /vol/vol1/lun`):

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. Se SnapDrive supporta una soluzione di multipathing di terze parti per UNIX o Utility host, scaricare il pacchetto software e il pacchetto applicativo del driver HBA dal sito Web del vendor HBA.*QLogic*: Per gli HBA QLogic, visitare il sito http://support.qlogic.com/[]. Tra i modelli OEM, selezionare NetApp. Individuare la versione del driver elencata nella matrice di supporto e scaricarla. *Emulex:* per gli HBA Emulex, visitare il sito http://www.emulex.com/ts/index.html[]. Da Download, selezionare NetApp. Individuare la versione del driver elencata nella matrice di supporto e scaricarla. Scarica anche il pacchetto di applicazioni Emulex dalla stessa posizione.
+
Se si utilizza un adattatore QLogic con connettività FC, scaricare lo script di riscan di QLogic dal sito Web di QLogic e copiarlo su `/root` percorso (ad esempio, `/root/dynamic-lun-rescan.sh`). Lo script di riscan di QLogic richiede la conferma dell'utente; SnapDrive per UNIX potrebbe bloccarsi a tempo indeterminato in questa fase di conferma. È possibile evitare questa conferma impostando la variabile `_QL_DISABLE_WARNING_` a. `1` nello script.

+
Le versioni precedenti di SnapDrive per UNIX utilizzavano script di riscansione SCSI specifici del vendor per eseguire la scansione delle LUN su FC e quindi copiare script specifici del vendor su `/root/dynamic-lun-rescan.sh`. Questo è stato reso disponibile fino a RHEL 5U3.

+
Per RHEL 5U4/ SLES 10SP2 e versioni successive, lo script di riscan è attualmente disponibile in `/usr/bin` directory. Se lo script di riscan non è disponibile nella directory, è presente insieme a. `sg3_utils` pacchetto.

+

NOTE: È necessario assicurarsi che il `sg3_utils` e. `sg3_utils-libs` Le librerie sono disponibili per le versioni Red Hat Enterprise Linux (RHEL) e Oracle Enterprise Linux (OEL). Tuttavia, il `sg3_utils` Le librerie sono disponibili per la versione di SUSE Linux Enterprise Server (SLES) in `scsci utility.rpm` pacchetto.

. In una configurazione FC, eseguire l'area delle porte HBA host e delle porte di destinazione utilizzando la configurazione dello zoning dello switch.
. Installare e configurare lo switch FC appropriato.
. Verificare i requisiti dello stack UNIX in SnapDrive.
. Installare o aggiornare SnapDrive per UNIX.
. Verificare l'installazione di SnapDrive per UNIX.
. Individuare il `snapdrive.conf` percorso del file.
. Configurare le seguenti variabili di configurazione in `snapdrive.conf` file:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Per ogni host, il tipo di multipathing, il tipo di trasporto, il file system e il tipo di gestore dei volumi dipendono l'uno dall'altro. La seguente tabella descrive tutte le possibili combinazioni:

+
|===
| Piattaforma host | Tipo di trasporto predefinito | Tipo di multipathing | fstype | vmtype 


 a| 
Linux
 a| 
iscsi
 a| 
nativempio
 a| 
ext4 o ext3
 a| 
lvm



 a| 
iscsi
 a| 
nessuno
 a| 
ext4 o ext3
 a| 
lvm



 a| 
FCP
 a| 
nessuno
 a| 
ext4 o ext3
 a| 
lvm



 a| 
FCP
 a| 
nativempio
 a| 
ext4 o ext3
 a| 
lvm

|===
+
La tabella precedente fornisce i valori supportati di `_multipathing-type_`, `_default-transport_`, `_fstype_`, e. `_vmtype_` variabili di configurazione.

+

NOTE: Se il protocollo di trasporto è `iSCSI`e il tipo di multipathing è impostato su `none`, È necessario arrestare il daemon multipath ed eseguire i comandi SnapDrive per UNIX.



. Salvare `snapdrive.conf` file.
+
SnapDrive per UNIX controlla automaticamente questo file ogni volta che viene avviato. Per rendere effettive le modifiche, riavviare il daemon SnapDrive per UNIX.



*Informazioni correlate*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[Le operazioni SnapRestore e Snapconnect non funzionano in Linux dopo la migrazione di tipo multipathing]

http://mysupport.netapp.com["Supporto NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Guida all'installazione di Linux Unified host Utilities 7.1"]
