---
permalink: linux-administration/task_estimating_the_storage_space_to_split_a_volume_clone.html 
sidebar: sidebar 
keywords: clone, split, snap, snapdrive, volume, estimate 
summary: 'La stima della suddivisione dei cloni consente di stimare lo spazio di storage richiesto (in MB) per suddividere un clone di un volume. A seconda della stima del clone split fornita da SnapDrive per UNIX, è possibile determinare la disponibilità di spazio per dividere un clone di volume.' 
---
= Stima dello spazio di storage per la suddivisione di un clone di volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La stima della suddivisione dei cloni consente di stimare lo spazio di storage richiesto (in MB) per suddividere un clone di volume. A seconda della stima del clone split fornita da SnapDrive per UNIX, è possibile determinare la disponibilità di spazio per dividere un clone di volume.

.Fasi
. Immettere il seguente comando per stimare lo spazio di storage richiesto per dividere un clone di volume.
+
`*snapdrive clone split estimate [-lun] _long_lun_name_ [long___lun_name__...] | [{-dg | -vg | -fs | -hostvol | -lvol} _file_spe_ [_file_spec_...]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose] [-dump | -dumpall]*`

+
Questa operazione visualizza le seguenti informazioni:

+
** Nome della risorsa
** Container - aggregato per FlexClone
** Required Space (spazio richiesto) - spazio necessario per dividere il clone del volume
** Spazio disponibile - spazio disponibile sul container
** Storage Status (Stato dello storage) - indica la disponibilità di spazio per una suddivisione del clone di un volume
** Spazio di proprietà - spazio occupato dal clone del volume
** Spazio condiviso - spazio occupato dal clone del volume insieme all'origine


+
Il `Owned Space` e. `Shared Space` viene visualizzato quando si utilizza `-verbose` opzione.



Nell'esempio riportato di seguito viene valutato lo spazio di storage necessario per suddividere un clone di un volume.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -fs /mnt/my_mnt2
Resource     Container  Required Available  Storage
                        Space(MB) Space(MB) Status
/mnt/my_mnt1  f3050-220  400      61500    AVAILABLE
              -111:aggr0
/mnt/my_mnt2  f3050-220  3292     1129     NOT AVAILABLE
              -112:aggr1
----
Per ogni specifica di file, SnapDrive per UNIX determina lo spazio necessario disponibile nel sistema di storage per suddividere un clone di volume. Qui, il `/mnt/my_mnt1` La specifica del file dispone dello spazio necessario per la suddivisione, pertanto lo stato dello storage viene visualizzato come DISPONIBILE. Mentre, il `/mnt/my_mnt2` La specifica del file non dispone dello spazio necessario per la suddivisione, pertanto lo stato dello storage viene visualizzato come NON DISPONIBILE.

Di seguito viene riportato un esempio di utilizzo di `-verbose` opzione. In alternativa, è possibile utilizzare `-v` opzione.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container Owned    Shared   Required Available Storage
                      Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220 32365  403      403     55875 AVAILABLE
             -111:aggr0
----