---
permalink: linux-administration/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, shot, list, command 
summary: 'Il comando SnapDrive snap show o list visualizza il nome del sistema di storage in cui viene creata la copia Snapshot, il nome host, la data e l"ora e così via.' 
---
= Visualizzazione di una copia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il comando `snapdrive snap show` oppure `list` Visualizza il nome del sistema di storage in cui viene creata la copia Snapshot, il nome host, la data e l'ora e così via.

.Fasi
. Immettere la seguente sintassi del comando per visualizzare una copia Snapshot:
+
`*snapdrive snap show [-snapname] long_snap_name [snap_name...] [-verbose]*`



Questa operazione visualizza almeno le seguenti informazioni sulla copia Snapshot:

* Il nome del sistema di storage in cui viene creata la copia Snapshot
* Il nome dell'host che ha eseguito la copia Snapshot
* Il percorso delle LUN nel sistema storage
* La data e l'ora di creazione della copia Snapshot
* Il nome della copia Snapshot
* I nomi dei gruppi di dischi inclusi nella copia Snapshot


*Esempio*: Di seguito sono riportati alcuni esempi `snapdrive snap show` comandi:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Esempio*: Questo esempio utilizza un carattere jolly per visualizzare informazioni sulle copie Snapshot disponibili su un determinato volume:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Esempio*: Questo esempio mostra una copia Snapshot di un albero di directory montato su NFS su un host Linux utilizzando il comando SnapDrive snap-list con `- verbose` opzione:

[listing]
----
# snapdrive snap list -fs /mnt/acctfs1 -v
snap name host date
snapped
------------------------------------------------------------------
----------
besser:/vol/vol1:acctfs-s1 childs Aug 8 18:58
/mnt/acctfs1
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: acctfs-s1 file system: type: nfs mountpoint:
/mnt/acctfs1
filer dir: besser:/vol/vol1
----
*Esempio*: Questo esempio esegue il comando SnapDrive SNAP show su un host Linux:

[listing]
----
# snapdrive snap show -snapname surf:/vol/vol1:swzldg5snapped
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
#
# ./linux/ix86/snapdrive snap show -v -snapname
surf:/vol/vol1:bagel5snapped >
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: bagel5snapped
Volume Manager: linuxlvm 1.0.3
disk group: dg5
host volume: vol1
host volume: vol2
host volume: vol3
lun path dev paths
-------------------------------------------------------
surf:/vol/vol1/glk19 /dev/sdu
----
*Esempio*: I seguenti esempi utilizzano il carattere jolly:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Esempio*: In questo esempio, l'utilizzo di un carattere jolly non è valido perché il carattere jolly si trova al centro del nome invece di essere posizionato alla fine:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----