---
permalink: linux-administration/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file, name 
summary: 'Se si desidera attivare un file di log, specificare un nome file come valore nella coppia nome-valore del file di log che si desidera attivare. Se si desidera disattivare un file, non immettere un valore per il parametro log file name (Nome file di registro).' 
---
= Attivazione e disattivazione dei file di log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera attivare un file di log, specificare un nome file come valore nella coppia nome-valore del file di log che si desidera attivare. Se si desidera disattivare un file, non immettere un valore per il parametro log file name (Nome file di registro).

Devi aver effettuato l'accesso come utente root.

.Fasi
. Aprire `snapdrive.conf` in un editor di testo.
. Scegliere l'opzione appropriata per attivare o disattivare un file di log.
+
|===
| Se si desidera... | Quindi... 


 a| 
*Attivare un file di log*
 a| 
 Specify a file name as the value in the name-value pair of the log file you want to enable. SnapDrive for UNIX only writes log files if it has the name of a file to write to. The default names for the log files are as follows:
** Log di audit: `sd-audit.log`
** Log di recovery: `sd-recovery.log`
** Log di traccia: `sd-trace.log`



NOTE: Il percorso di questi file può variare a seconda del sistema operativo host in uso.



 a| 
*Disattiva un file di log*
 a| 
 Do not enter a value for the log file name parameter. If you do not supply a value, there is no file name to which SnapDrive for UNIX can write the log information.
*Esempio* questo esempio disattiva il file di log di audit. `audit-log-file=""`

|===
. Salvare `snapdrive.conf` dopo aver apportato tutte le modifiche.
+
SnapDrive per UNIX controlla automaticamente questo file ogni volta che viene avviato. Per rendere effettive le modifiche, riavviare il daemon SnapDrive per UNIX.


