---
permalink: aix/concept_verify_that_the_hosts_are_ready.html 
sidebar: sidebar 
keywords: snap, snapdrive, verify, host, ready 
summary: 'Verificare che gli host siano pronti. Per avviare le operazioni di verifica, verificare innanzitutto se l"host è connesso al sistema di storage immettendo il comando ping filername.' 
---
= Verificare che gli host siano pronti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare che gli host siano pronti. Per avviare le operazioni di verifica, verificare innanzitutto se l'host è connesso al sistema di storage immettendo il `ping filername` comando.

È inoltre necessario confermare che gli host e il sistema di storage possono comunicare tra loro. Per confermare, eseguire `snapdrive storage show -all` controllare e controllare se gli host e il sistema di storage stanno comunicando. Verificare che gli host siano pronti eseguendo alcune operazioni:

* Verificare che l'host e il sistema di storage siano stati configurati correttamente seguendo le istruzioni riportate nella documentazione delle utility host per l'host.
* Verificare di disporre di una configurazione che utilizzi NFS e configurare il file di esportazione.
* Verificare che l'host soddisfi i requisiti minimi per SnapDrive per UNIX, incluse le patch del sistema operativo richieste.


*Informazioni correlate*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["Riferimento NFS per ONTAP 9"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1401220["Guida all'accesso ai file e alla gestione dei protocolli di Data ONTAP 8.2 per 7-Mode"]

http://mysupport.netapp.com["Supporto NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["GUIDA all'installazione e all'installazione DI AIX host Utilities 6.0"]
