---
permalink: aix/concept_restoring_multiple_storage_entities.html 
sidebar: sidebar 
keywords: restore, multiple, storage, entities, snap, snapdrive 
summary: È possibile ripristinare una copia Snapshot che contiene più entità di storage. 
---
= Ripristino di più entità di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare una copia Snapshot che contiene più entità di storage.

Per ripristinare una copia Snapshot contenente entità di storage che risiedono su più sistemi di storage di destinazione, è necessario soddisfare i seguenti requisiti:

* Le entità di storage specificate al prompt dei comandi devono risiedere in un singolo sistema di storage o in una coppia ha.
* Il nome del volume del sistema di storage di origine deve corrispondere al nome del volume del sistema di storage di destinazione.
* È necessario impostare `snapmirror-dest-multiple-filervolumes-enabled` argomento in `snapdrive.conf` file su on.


È possibile utilizzare un comando per ripristinare le entità di storage che risiedono su un singolo sistema storage o su una coppia ha.
