---
permalink: aix/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, example, autosupport, message, support 
summary: SnapDrive per UNIX fornisce esempi per diversi scenari. Il contenuto di un messaggio AutoSupport in tutti gli esempi è sostanzialmente lo stesso indipendentemente dal sistema operativo in uso. 
---
= Esempi di messaggi AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX fornisce esempi per diversi scenari. Il contenuto di un messaggio AutoSupport in tutti gli esempi è sostanzialmente lo stesso indipendentemente dal sistema operativo in uso.

Esempio: Aggiunta di un nuovo sistema storage

L'esempio seguente è un messaggio inviato da un host denominato `_aix207-116_`:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="ohio configured"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Esempio: Riavviare il Daemon

SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage quando si riavvia il daemon:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage quando un'operazione di connessione dello storage non riesce:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="4"
        category="storage connect failed"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp,1384: LUN /vol/vol0/test1 on storage system ohio already mapped to initiators in igroup aix207-116_fcp_SdIg at ID 0."/
----
SnapDrive per UNIX invia il seguente messaggio AutoSupport al sistema di storage quando un `snap create` operazione riuscita:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp, snapshot_name=snap1"
----