---
permalink: aix/concept_operations_performed_on_stand_alone_unix_systems.html 
sidebar: sidebar 
keywords: snap, snapdrive, operation, stand, alone 
summary: SnapDrive per UNIX su sistemi UNIX standalone consente di creare storage e gestire copie Snapshot di LUN, file system, volumi logici e gruppi di dischi. 
---
= Operazioni eseguite su sistemi UNIX standalone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX su sistemi UNIX standalone consente di creare storage e gestire una copia Snapshot di LUN, file system, volumi logici e gruppi di dischi.

* Creare storage che includa LUN, file system, volumi logici e gruppi di dischi.
+
Una volta creato lo storage, è possibile aumentarne o ridurne la capacità, connetterlo a un host o scollegarlo e visualizzare le informazioni di configurazione relative allo storage.

* Creare una copia Snapshot di uno o più gruppi di volumi su un sistema storage.
+
La copia Snapshot può contenere file system, volumi logici, gruppi di dischi, LUN e strutture di directory NFS. Dopo aver creato una copia Snapshot, è possibile rinominare, ripristinare o eliminare la copia Snapshot. È inoltre possibile collegare una copia Snapshot a una posizione diversa sullo stesso host o su un altro host. Dopo aver collegato la copia Snapshot, è possibile visualizzare e modificare il contenuto o disconnettersi. È inoltre possibile visualizzare informazioni sulle copie Snapshot create.


