---
permalink: aix/task_estimating_the_storage_space_to_split_a_lun_clone.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, space, split, lun, clone 
summary: 'La stima della suddivisione dei cloni consente di stimare lo spazio di storage richiesto (in MB) per dividere un clone LUN. A seconda della stima della suddivisione dei cloni fornita da SnapDrive per UNIX, è possibile determinare la disponibilità di spazio per suddividere un clone del LUN.' 
---
= Stima dello spazio di storage per la suddivisione di un clone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La stima della suddivisione dei cloni consente di stimare lo spazio di storage richiesto (in MB) per suddividere un clone del LUN. A seconda della stima della suddivisione dei cloni fornita da SnapDrive per UNIX, è possibile determinare la disponibilità di spazio per suddividere un clone del LUN.

.Fasi
. Immettere il seguente comando per stimare lo spazio di storage richiesto per dividere un clone del LUN.
+
`*snapdrive clone split estimate [-lun]_long_lun_name_ [_long_lun_name_...] | [{-dg | -vg | -fs | -hostvol | -lvol}__file_spec__ [_file_spec_...]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose]*`

+
Questa operazione visualizza le seguenti informazioni:

+
** Nome della risorsa
** Container - Volume per un clone del LUN
** Required Space (spazio richiesto) - spazio necessario per dividere un clone del LUN
** Spazio disponibile - spazio disponibile sul container
** Storage Status (Stato storage) - indica la disponibilità di spazio per un clone split del LUN
** Spazio di proprietà - spazio occupato dal clone del LUN
** Spazio condiviso - spazio occupato dal clone del LUN insieme all'origine


+
Il `Owned Space` e. `Shared Space` viene visualizzato quando si utilizza `-verbose` opzione.



Nell'esempio riportato di seguito viene valutato lo spazio di storage necessario per suddividere un clone del LUN.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1
Resource     Container Required Available Storage
                       Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  5120    9986    AVAILABLE
             -112:/vol/vol_1
----
Di seguito viene riportato un esempio di utilizzo di `-verbose` opzione. In alternativa, è possibile utilizzare `-v` opzione.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container  Owned    Shared   Required Available Storage
                       Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  365   403      5120     9986 AVAILABLE
             -112:/vol/vol_1
----