---
permalink: aix/task_configuring_user_credentials_on_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, user, credentials, operations, manager, console, configure 
summary: 'L"amministratore di SnapDrive per UNIX riceve le credenziali utente dall"amministratore della console di Operations Manager. Queste credenziali utente devono essere configurate su SnapDrive per UNIX per le corrette operazioni di storage.' 
---
= Configurazione delle credenziali utente su SnapDrive per UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'amministratore di SnapDrive per UNIX riceve le credenziali utente dall'amministratore della console di Operations Manager. Queste credenziali utente devono essere configurate su SnapDrive per UNIX per le corrette operazioni di storage.

.Fasi
. Configurare sd-admin sul sistema storage.
+
[listing]
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----
. Configurare il nome host sd sul sistema di storage.
+
[listing]
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----
. Verificare i passaggi 1 e 2 utilizzando `snapdrive config list` comando.
+
[listing]
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----
. Configurare SnapDrive per UNIX per utilizzare RBAC (role-based access control) della console di Operations Manager impostando la variabile di configurazione `rbac-method="dfm"` in `snapdrive.conf` file.
+

NOTE: Le credenziali dell'utente vengono crittografate e salvate nel file esistente `.sdupw` file. La posizione predefinita del file precedente è `/opt/NetApp/snapdrive/.sdupw`.


