---
permalink: aix/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, multipathing, hba 
summary: 'Per utilizzare il multipathing in SnapDrive per UNIX, è necessario completare i passaggi che includono l"installazione e l"avvio dell"HBA. Se si utilizza una soluzione multipathing non NetApp, è necessario scaricare il pacchetto software e applicativo dal sito Web del vendor HBA.' 
---
= Abilitazione del multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per utilizzare il multipathing in SnapDrive per UNIX, è necessario completare i passaggi che includono l'installazione e l'avvio dell'HBA. Se si utilizza una soluzione multipathing non NetApp, è necessario scaricare il pacchetto software e applicativo dal sito Web del vendor HBA.

Il sistema deve eseguire le versioni correnti dei componenti del sistema FC e iSCSI.

http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

.Fasi
. Installare gli HBA supportati prima di installare il software host Utilities appropriato.
+

NOTE: SnapDrive per UNIX supporta HBA multivendor.

. Avviare il servizio HBA.
+
Se il servizio HBA non è in esecuzione, viene visualizzato il seguente messaggio di errore quando si eseguono i comandi SnapDrive per UNIX, ad esempio `snapdrive storage create` e. `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
È necessario verificare che il numero di percorsi richiesto sia attivo e in esecuzione. È possibile verificare i percorsi utilizzando l'utility sanlun, inclusa nel software Utility host. Ad esempio, nella configurazione multipathing FC, è possibile utilizzare `sanlun fcp show adapter -v` comando.

+
Nell'esempio seguente, sono presenti due porte HBA (fcd0 e fcd1) collegate all'host e funzionanti (stato della porta). È possibile disporre di un solo HBA o iSCSI Initiator ed è necessario configurare il multipathing fornendo più di un percorso per i LUN di destinazione.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Se su un host è attivato il multipathing, sono visibili più percorsi per lo stesso LUN. È possibile utilizzare `sanlun lun show all` per verificare i percorsi. Nell'esempio seguente, è possibile trovare più percorsi per lo stesso LUN (`fish: /vol/vol1/lun`):

+
[listing]
----
filer:         lun-pathname        device filename  adapter    protocol   lun size              lun state
    filer_1:        fish/vol/vol1/l1      hdisk36          fcs0       FCP       5m   (5242880)        GOOD
    filer_2:        fish/vol/vol0/lunKr   hdisk39          fcs0       FCP       100m (104857600)      GOOD
    filer_3:        fish/vol/vol0/testaix hdisk2           fcs0       FCP       200m (209715200)      GOOD
    filer_4:        fish/vol/vol1/l1      hdisk45          fcs1       FCP       5m   (5242880)        GOOD
----
. In una configurazione FC, eseguire l'area delle porte HBA host e delle porte di destinazione utilizzando la configurazione dello zoning dello switch.
. Installare e configurare lo switch FC o iSCSI appropriato.
. Verificare i requisiti dello stack UNIX in SnapDrive.
. Installare o aggiornare SnapDrive per UNIX.
. Verificare l'installazione di SnapDrive per UNIX.
. Individuare il `snapdrive.conf` percorso del file.
. Configurare le seguenti variabili di configurazione in `snapdrive.conf` file:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Per ogni host, il tipo di multipathing, il tipo di trasporto, il file system e il tipo di gestore dei volumi dipendono l'uno dall'altro. La seguente tabella descrive tutte le possibili combinazioni:



+
|===
| Piattaforma host | Tipo di trasporto predefinito | Tipo di multipathing | fstype | vmtype 


 a| 
AIX
 a| 
FCP
 a| 
assoluto
 a| 
jfs2 o jfs
 a| 
lvm



 a| 
nativempio
 a| 
jfs2 o jfs
 a| 
lvm



 a| 
dmp
 a| 
vxfs
 a| 
vxvm

|===
+
La tabella precedente fornisce i valori supportati di `_multipathing-type_`, `_default-transport_`, `_fstype_`, e. `_vmtype_` variabili di configurazione.

. Salvare `snapdrive.conf` file.
+
SnapDrive per UNIX controlla automaticamente questo file ogni volta che viene avviato. Per rendere effettive le modifiche, riavviare il daemon SnapDrive per UNIX.



*Informazioni correlate*

http://mysupport.netapp.com["Supporto NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["GUIDA all'installazione e all'installazione DI AIX host Utilities 6.0"]
