---
permalink: aix/task_creating_a_filesystem_on_a_lunand_setting_up_thelun_automatically.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, file, system, create 
summary: È possibile creare un file system su un LUN utilizzando SnapDrive per UNIX. SnapDrive per UNIX crea automaticamente il LUN associato. 
---
= Creazione di un file system su un LUN e configurazione automatica del LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un file system su un LUN utilizzando SnapDrive per UNIX. SnapDrive per UNIX crea automaticamente il LUN associato.

.Fasi
. Nella riga di comando, immettere il seguente comando:
+
`*snapdrive storage create -fs _file_spec_ -nolvm [-fstype type] [-fsopts options] [-mntopts options] [-nopersist] -filervol _long_filer_path_ -lunsize _size_ [-igroup _ig_name [ig_name ...]]_ [{-reserve | -noreserve }]*`

+
SnapDrive per UNIX crea il file system specificato e crea un LUN per questo file sul sistema di storage specificato. Esegue tutte le attività associate alla preparazione e al rilevamento degli host per le LUN, nonché il mapping e la connessione delle LUN all'entità host.





== Esempi:

*Creazione di un file system da 100 MB direttamente su un LUN:*

[listing]
----
# snapdrive storage create -fs /mnt/acct1 -filervol acctfiler:/vol/vol1 -lunsize 100m -nolvm
----
*Creazione di un file system su un LUN raw senza alcun gestore di volumi:*

[listing]
----
# snapdrive storage create -fs /mnt/vxfs2 -fstype vxfs -lun
snoopy:/vol/vol1/lunVxvm2 -lunsize 50m -nolvm
LUN snoopy:/vol/vol1/lunVxvm2 ... created
mapping new lun(s) ... done
discovering new lun(s) ... done
LUN to device file mappings:
- snoopy:/vol/vol1/lunVxvm2 => /dev/vx/dmp/Disk_1
file system /mnt/vxfs2 created
----