---
permalink: solaris/concept_storage_provisioning_for_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, vmware, vmotion, support, unix 
summary: 'SnapDrive per UNIX consente di scollegare e collegare i LUN RDM prima e dopo VMware VMotion. Una volta completata l"operazione VMotion, è possibile eseguire le operazioni di storage necessarie per il sistema storage.' 
---
= Supporto di VMware VMotion in SnapDrive per UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX consente di scollegare e collegare i LUN RDM prima e dopo VMware VMotion. Una volta completata l'operazione VMotion, è possibile eseguire le operazioni di storage necessarie per il sistema storage.

*A proposito di VMware VMotion:*

VMware VMotion consente di spostare un sistema guest da un server ESX a un altro server ESX.

Per disconnettere e connettere i LUN RDM in SnapDrive per UNIX, è necessario eseguire le seguenti operazioni.

*Prima di VMotion*

È necessario utilizzare `snapdrive storage disconnect` Comando per rimuovere i mapping per i LUN RDM. La seguente sintassi:

`*snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._]*`

*Dopo VMotion*

Una volta completato VMotion, è necessario utilizzare `snapdrive storage connect` Comando per connettere LUN RDM. La seguente sintassi:

`*snapdrive storage connect -lun _long_lun_name_ [_lun_name..._]*`

*Informazioni correlate*

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[Limitazioni delle LUN RDM gestite da SnapDrive]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[Configurazione della console di storage virtuale per SnapDrive per UNIX]

xref:concept_guest_os_preparation_for_installing_sdu.adoc[Preparazione del sistema operativo guest per l'installazione di SnapDrive per UNIX]

xref:task_considerations_for_provisioning_rdm_luns.adoc[Considerazioni per il provisioning dei LUN RDM]
