---
permalink: solaris/concept_what_the_web_service_and_daemon_are.html 
sidebar: sidebar 
keywords: snap, snapdrive, web, service, daemon 
summary: 'Il servizio Web SnapDrive per UNIX fornisce un"interfaccia uniforme per tutti i prodotti NetApp SnapManager e di terze parti per integrarsi perfettamente con SnapDrive per UNIX. Per utilizzare i comandi dell"interfaccia della riga di comando in SnapDrive per UNIX, è necessario avviare il daemon.' 
---
= Cosa sono il servizio Web e il daemon
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il servizio Web SnapDrive per UNIX fornisce un'interfaccia uniforme per tutti i prodotti NetApp SnapManager e di terze parti per integrarsi perfettamente con SnapDrive per UNIX. Per utilizzare i comandi dell'interfaccia a riga di comando (CLI) in SnapDrive per UNIX, è necessario avviare il daemon.

Diversi prodotti NetApp SnapManager utilizzano l'interfaccia a riga di comando (CLI) per comunicare con SnapDrive per UNIX. L'utilizzo della CLI pone un limite alle performance e alla gestibilità di SnapManager e SnapDrive per UNIX. Quando si utilizza il daemon SnapDrive per UNIX, tutti i comandi funzionano come un processo unico. Il servizio daemon non influisce sul modo in cui vengono utilizzati i comandi SnapDrive per UNIX.

Il servizio Web SnapDrive per UNIX consente alle applicazioni di terze parti di integrarsi perfettamente con SnapDrive per UNIX. Interagiscono con SnapDrive per UNIX utilizzando API.

All'avvio del daemon, SnapDrive per UNIX verifica prima se il daemon è in esecuzione. Se il daemon non è in esecuzione, avvia il daemon. Se il daemon è già in esecuzione e si tenta di avviarlo, SnapDrive per UNIX visualizza il messaggio:

`snapdrive daemon is already running`

È possibile controllare lo stato del daemon per verificare se SnapDrive per UNIX è in esecuzione o meno. Controllare lo stato prima di decidere di avviare il daemon. Se un utente diverso dall'utente root tenta di controllare lo stato, SnapDrive per UNIX verifica le credenziali dell'utente e visualizza il messaggio:

`snapdrive daemon status can be seen only by root user`

Quando si tenta di arrestare il daemon, SnapDrive per UNIX verifica le credenziali. Se si è un utente diverso da quello root, SnapDrive per UNIX visualizza il messaggio

`snapdrive daemon can be stopped only by root user`

Dopo aver interrotto il daemon, è necessario riavviare il daemon SnapDrive per UNIX per rendere effettive le modifiche apportate al file di configurazione o a qualsiasi modulo. Se un utente diverso dall'utente root tenta di riavviare il daemon SnapDrive per UNIX, SnapDrive per UNIX verifica le credenziali dell'utente e visualizza il messaggio

`snapdrive daemon can be restarted only by root user`
