---
permalink: solaris/concept_after_rebooting_the_host_os_and_cluster_services_fail_to_start.html 
sidebar: sidebar 
keywords: reboot, host, os, cluster, fail, start 
summary: Su un host Solaris 10, se il file system non viene montato dopo il riavvio, il sistema operativo e il cluster non si avviano. 
---
= Dopo il riavvio dell'host, il sistema operativo e i servizi del cluster non si avviano
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Su un host Solaris 10, se il file system non viene montato dopo il riavvio, il sistema operativo e il cluster non si avviano.

Dopo aver riavviato l'host Solaris 10, se il servizio `svc:/system/filesystem/local` Non riesce a montare uno dei seguenti file system, il sistema operativo dipendente o i servizi cluster non si avviano.

* File system locale
* File system condiviso



NOTE: Il file system precedente deve essere creato da SnapDrive per UNIX.



== Soluzione alternativa

. Individuare il servizio che non è stato avviato dopo il riavvio utilizzando il seguente comando:
+
`svcs -vx /network/inetd`

+
*Esempio:*

+
[listing]
----
# svcs -vx /network/inetd
svc:/network/inetd:default (inetd)
State: offline since Fri 25 May 2008 04:06:59 PM IST
Reason: Service svc:/system/filesystem/local:default
is not running because a method failed.
----
. Se il `service/system/filesystem/local:default` non riesce, individuare il file system persistente che non è riuscito a montare utilizzando il seguente comando:
+
`tail /var/svc/log/system-filesystem-local:default.log`

+
*Esempio:*

+
[listing]
----
# tail /var/svc/log/system-filesystem-local:default.log
[ May 25 15:58:35 Method "start" exited with status 95 ]
[ May 25 16:07:17 Executing start method
("/lib/svc/method/fs-local") ]
UX:vxfs fsck: ERROR: V-3-20693: cannot access device
/dev/vx/rdsk/dg2/fs1_SdHv:
UX:vxfs mount: ERROR: V-3-20003: Cannot open
/dev/vx/dsk/dg2/fs1_SdHv: No such device or address
UX:vxfs mount: ERROR: V-3-24996: Unable to get disk
layout version
WARNING: /sbin/mountall -l failed: exit status 1
[ May 25 16:07:18 Method "start" exited with status 95 ]
----
. Commentare le voci in `/etc/vfstab` per il file system che non è riuscito a montare dopo il riavvio dell'host.
. Riavviare il servizio del sistema operativo: `svc:/system/filesystem/local:default` eseguendo i seguenti comandi:
+
.. `svcadm disable`
+
`svc:/system/filesystem/local:default`

.. `svcadm enable`
+
`svc:/system/filesystem/local:default`



+
Viene avviato il sistema operativo e il servizio cluster.

. Per il file system locale che non è stato possibile montare, attenersi alla seguente procedura:
+
.. Montare manualmente il file system.
.. Annullare il commento di `/etc/vfstab` entry-level.


. Per i servizi cluster, attenersi alla seguente procedura:
+
.. Utilizzare `cfsmount` comando per verificare se i file system condivisi sono montati correttamente.
.. Annullare il commento di `/etc/vfstab` su tutti i nodi del cluster per questo file system.
+
`svcadm enable`

+
`svc:/system/filesystem/local:default`



. Se il file system locale o cluster non riesce a essere montato anche dopo aver completato i passaggi precedenti, contattare il supporto tecnico di NetApp.

