---
permalink: solaris/concept_automatic_detection_of_host_entities.html 
sidebar: sidebar 
keywords: snap, snapdrive, automatic, detection, host 
summary: 'SnapDrive per UNIX rileva automaticamente la configurazione dell"entità host per alcuni comandi. Alcuni comandi di storage SNAP richiedono solo il nome dell"entità host. In questi casi, non è necessario specificare il tipo di entità host.' 
---
= Rilevamento automatico delle entità host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX rileva automaticamente la configurazione dell'entità host per alcuni comandi. Alcuni `snap storage` i comandi richiedono solo il nome dell'entità host. In questi casi, non è necessario specificare il tipo di entità host.

I seguenti comandi sono abilitati per il rilevamento automatico:

* `storage delete`
* `storage resize`
* `snap create`
* `snap restore`
* `snap connect`
* `snap list`


Quando l'entità host esiste, SnapDrive per UNIX rileva automaticamente il tipo di entità host. In questo caso, è necessario fornire solo il nome dell'entità host; non è necessario specificare il tipo. SnapDrive `snap` e alcuni `storage` i comandi richiedono anche solo il nome dell'entità host; non è necessario specificare il tipo.

Il rilevamento automatico dei comandi richiede più tempo per SnapDrive 4.1 e versioni successive, in quanto raccoglie i dettagli di tutte le risorse di storage. Se si desidera una risposta più rapida, specificare la specifica del file con i comandi SnapDrive per UNIX.

È possibile attivare il rilevamento automatico per l'operazione di eliminazione dello storage eseguendo `snapdrive storage delete` comando.

*Esempio 1:*

[listing]
----
snapdrive storage delete host_dg my_fs -full
----
Nell'esempio, `host_dg` e. `my_fs` vengono rilevati automaticamente.

*Esempio 2:*

[listing]
----
snapdrive storage delete mydg -fs myfs -full
----
Nell'esempio, il `mydg` il gruppo di dischi viene rilevato automaticamente.

È possibile attivare il rilevamento automatico per l'operazione di ridimensionamento dello storage eseguendo `snapdrive storage resize` comando.

*Ad esempio*:

[listing]
----
[root@lnx197-132 ~]# snapdrive storage resize mydg23 -addlun -growby 10m
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
        discovering filer LUNs in disk group mydg23...done
        LUN bart:/vol/voldm/mydg23-1_SdLun ... created

        mapping new lun(s) ... done
        discovering new lun(s) ... done.
        initializing LUN(s) and adding to disk group mydg23...done
Disk group mydg23 has been resized
----
È possibile attivare il rilevamento automatico per l'operazione di creazione SNAP eseguendo `snapdrive snap create` comando.

*Ad esempio*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap create mydg22 mydg23 /mnt/mnt12 -snapname new_snap
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec '/mnt/mnt12 ' in progress ... detected as file system

Starting snap create /dev/mapper/mydg22, /dev/mapper/mydg23, /mnt/mnt12
  WARNING:  DO NOT CONTROL-C!
            If snap create is interrupted, incomplete snapdrive
                 generated data may remain on the filer volume(s)
                 which may interfere with other snap operations.
Successfully created snapshot new_snap on bart:/vol/voldm

        snapshot new_snap contains:
        disk group mydg22
        disk group mydg23
        disk group dg121 containing host volumes
                lv121 (filesystem: /mnt/mnt12)
----
È possibile attivare il rilevamento automatico per l'operazione di connessione SNAP eseguendo `snapdrive snap connect` comando.

*Ad esempio*:

[listing]
----
[root@lnx197-132 ~]# snapdrive snap connect mydg22 xxx mydg23 yyy -snapname bart:/vol/voldm:snap_1
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'xxx' in progress ...
        xxx does not exist - Taking xxx as a destination to fspec mydg22Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec 'yyy' in progress ...
        yyy does not exist - Taking yyy as a destination to fspec mydg23
 connecting mydg22:
        LUN copy mydg22_SdLun_0 ... created
                 (original: bart:/vol/voldm/mydg22_SdLun)

        mapping new lun(s) ... done

 connecting mydg23:
        LUN copy mydg23_SdLun_1 ... created
                 (original: bart:/vol/voldm/mydg23_SdLun)

        mapping new lun(s) ... done
        discovering new lun(s) ... done
        Importing xxx, yyy
Successfully connected to snapshot bart:/vol/voldm:snap_1
        disk group xxx
        disk group yyy
----
È possibile attivare il rilevamento automatico per l'operazione di ripristino SNAP eseguendo `snapdrive snap restore` comando.

*Ad esempio*:

[listing]
----
snapdrive snap restore bart:/vol/voldm/lun44 /mnt/fs3 fs5_SdDg/fs5_SdHv fs4_SdDg -snapname bart:/vol/voldm:toi_snap

        Auto detection of file_spec(s) in progress ...
               - 'bart:/vol/voldm/lun44' detected as LUN.
               - '/mnt/fs3' detected as file system.
               - 'fs5_SdDg/fs5_SdHv' detected as logical volume.
               - 'fs4_SdDg' detected as disk group.
        Starting to restore /dev/mapper/fs4_SdDg, /mnt/fs3, /dev/mapper/fs5_SdDg-fs5_SdHv, bart:/vol/voldm/lun44
         WARNING:  This can take several minutes.
           DO NOT CONTROL-C!
           If snap restore is interrupted, the filespecs
           being restored may have inconsistent or corrupted
           data.
       For detailed progress information, see the log file /var/log/sd-recovery.log
           Importing fs4_SdDg, fs3_SdDg, fs5_SdDg
           Successfully restored snapshot toi_snap on bart:/vol/voldm
       disk group fs4_SdDg containing host volumes
               fs4_SdHv (filesystem: /mnt/fs4)
       disk group fs3_SdDg containing host volumes
               fs3_SdHv (filesystem: /mnt/fs3)
       disk group fs5_SdDg containing host volumes
               fs5_SdHv (filesystem: /mnt/fs5)
       raw LUN: bart:/vol/voldm/lun44
----
SnapDrive non supporta il rilevamento automatico delle operazioni di connessione SNAP e ripristino SNAP per una specifica del file errata.

È possibile attivare il rilevamento automatico per l'operazione di snap-list eseguendo `snapdrive snap list` comando.

*Ad esempio*:

[listing]
----
root@lnx197-132 ~]# snapdrive snap list -snapname bart:/vol/voldm:snap_1

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
[root@lnx197-132 ~]# snapdrive snap list mydg23
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
bart:/vol/voldm:all                  lnx197-132.xyz.com Apr  9 00:16 mydg22 mydg23 fs1_SdDg
bart:/vol/voldm:you                  lnx197-132.xyz.com Apr  8 21:03 mydg22 mydg23
bart:/vol/voldm:snap_2                  lnx197-132.xyz.com Apr  8 18:05 mydg22 mydg23
----