---
permalink: solaris/concept_manual_pages_installed_by_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, man, page, install 
summary: SnapDrive per UNIX offre pagine man in diversi formati. 
---
= Pagine man installate da SnapDrive per UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive per UNIX offre pagine man in diversi formati.

Le pagine man sono disponibili al seguente indirizzo:

* `/opt/NTAPsnapdrive/docs/snapdrive.1`
* `/opt/NTAPsnapdrive/docs/snapdrived.1`
* `/opt/NTAPsnapdrive/docs/snapdrive.1.html`
* `/opt/NTAPsnapdrive/docs/snapdrived.1.html`
* `/opt/NTAPsnapdrive/docs/solaris_info.1`
* `/opt/NTAPsnapdrive/docs/brocade_info.1`
* `/opt/NTAPsnapdrive/docs/mcdata_info.1`
* `/opt/NTAPsnapdrive/docs/cisco_info.1`
* `/opt/NTAPsnapdrive/docs/filer_info.1`
* `/opt/NTAPsnapdrive/docs/snapdrive.dc.1`


Se si installa SnapDrive per UNIX in una sparse root zone, non verranno aggiunte pagine man all'indirizzo `/usr/share/man/` perché `/usr/share/man/` viene montato come file system di sola lettura. Per estrarre le pagine man in una sparse root zone, eseguire `pkgtrans NTAPsnapdrive.pkg /tmp` comando. Dopo aver eseguito il comando, le pagine man vengono estratte in `/tmp/NTAPsnapdrive/root/opt/NTAPsnapdrive/docs` .
