---
permalink: solaris/reference_host_side_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, host, side, command, line 
summary: I comandi SnapDrive per UNIX vengono utilizzati per le operazioni sul lato host. 
---
= Righe di comando lato host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I comandi SnapDrive per UNIX vengono utilizzati per le operazioni sul lato host.

La seguente tabella fornisce diverse opzioni della riga di comando per le operazioni sul lato host.

|===
| Operazione | Opzione della riga di comando 


 a| 
Connessione host
 a| 
`snapdrive host connect -lun _long_lun_name_ [_lun_name ..._] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -nolvm -lun _long_lun_name_ [-nopersist][-mntopts options] [-fstype _type_] [-vmtype _type_]`



 a| 
`snapdrive host connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name_][-nopersist] [-mntopts _options_][-vmtype _type_]`



 a| 
Disconnessione host
 a| 
`snapdrive host disconnect-lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`



 a| 
`snapdrive host disconnect {-vg | -dg | -fs | -lvol | -hostvol} _file_spec_[_file_spec_ ...][{-vg | -dg | -fs | -lvol | -hostvol} _file_spec_ [_file_spec_ ...]...] [-full] [-fstype _type_] [-vmtype _type_]`

|===