---
permalink: solaris/task_decompressing_the_software_package_you_downloaded.html 
sidebar: sidebar 
keywords: snap, snapdrive, download, decompress, software, package 
summary: 'Per installare SnapDrive su un host Solaris, è necessario scaricare e decomprimere il pacchetto NTAPsnapdrive_Sun_x86_5.2.tar.Z o NTAPsnapdrive_Sun_sparc_5.2.tar.Z. Il pacchetto software dipende dall"utilizzo di Solaris su piattaforma x86 o SPARC.' 
---
= Download e decompressione del pacchetto software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per installare SnapDrive su un host Solaris, è necessario scaricare e decomprimere il pacchetto NTAPsnapdrive_Sun_x86_5.2.tar.Z o NTAPsnapdrive_Sun_sparc_5.2.tar.Z. Il pacchetto software dipende dall'utilizzo di Solaris su piattaforma x86 o SPARC.

.Fasi
. Scaricare il pacchetto software NTAPsnapdrive_Sun_x86_5.2.tar.Z o NTAPsnapdrive_Sun_sparc_5.2.tar.Z dal sito di supporto NetApp, a seconda che si utilizzi Solaris su x86 o SPARC.
. Accedere alla directory in cui è stato scaricato il file compresso.
+
Ad esempio, per accedere alla directory /tmp, immettere il seguente comando:

+
`*# cd /tmp*`

. Per decomprimere il pacchetto software per Solaris su x86, immettere il seguente comando:
+
`*# uncompress NTAPsnapdrive_sun_x86_5.2.tar.Z*`

+
Per Solaris su SPARC, immettere il seguente comando:

+
`*NTAPsnapdrive_sun_sparc_5.2.tar.Z*`

. Per estrarre il file per Solaris su x86, immettere il seguente comando:
+
`*# tar -xvf NTAPsnapdrive_sun_x86_5.2.tar*`

+
Per Solaris su SPARC, immettere il seguente comando:

+
`*tar -xvf NTAPsnapdrive_sun_sparc_5.2.tar*``



*Informazioni correlate*

http://mysupport.netapp.com["Supporto NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]
