---
permalink: solaris/task_enabling_thin_provisioning_for_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, thin, provisioning, lun 
summary: È possibile utilizzare SnapDrive per UNIX per eseguire il thin provisioning sul sistema storage. Il thin provisioning viene anche definito riserva di spazio. 
---
= Abilitazione del thin provisioning per LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare SnapDrive per UNIX per eseguire il thin provisioning sul sistema storage. Il thin provisioning viene anche definito riserva di spazio.

.Fasi
. Impostare `_space-reservations-enabled_` valore della variabile di configurazione a. `_on_`.
+
È inoltre possibile abilitare il thin provisioning utilizzando `-reserve` e. `-noreserve` parametri.

+
Il parametro sovrascrive il valore menzionato nella variabile -space-reservations-enabled.

+
È possibile utilizzare -Reserve e -noreserve con i seguenti comandi per attivare o disattivare la prenotazione LUN:

+
** `snapdrive storage create`
** `snapdrive storage resize`
** `snapdrive snap connect`
** `snapdrive snap restore`


+
Per impostazione predefinita, SnapDrive per UNIX consente la prenotazione dello spazio per operazioni di creazione dello storage nuove o nuove. Per le operazioni di ripristino SNAP e connessione SNAP, utilizza la riserva di spazio presente nella copia Snapshot se `_-reserve_` oppure `_-noreserve_` i parametri non vengono specificati nella riga di comando o se il valore nel file di configurazione non è commentato.


